/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zzc_androidtrain_jnitest_HelloJni */

#ifndef _Included_com_zzc_androidtrain_jnitest_HelloJni
#define _Included_com_zzc_androidtrain_jnitest_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zzc_androidtrain_jnitest_HelloJni
 * Method:    stringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zzc_androidtrain_jnitest_HelloJni_stringFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
