/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zzc_androidtrain_apk_patch_FileDiffer */

#ifndef _Included_com_zzc_androidtrain_apk_patch_FileDiffer
#define _Included_com_zzc_androidtrain_apk_patch_FileDiffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zzc_androidtrain_apk_patch_FileDiffer
 * Method:    genDifferFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zzc_androidtrain_apk_1patch_FileDiffer_genDifferFile
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_zzc_androidtrain_apk_patch_FileDiffer
 * Method:    fileCombine
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zzc_androidtrain_apk_1patch_FileDiffer_fileCombine
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
