/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zzc_androidtrain_qrcode_zbar_Zbar */

#ifndef _Included_com_zzc_androidtrain_qrcode_zbar_Zbar
#define _Included_com_zzc_androidtrain_qrcode_zbar_Zbar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zzc_androidtrain_qrcode_zbar_Zbar
 * Method:    decode
 * Signature: (II[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zzc_androidtrain_qrcode_zbar_Zbar_decode
  (JNIEnv *, jobject, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
